name: Install Docker.   
on: 
  workflow_call:
    inputs: 
      os:
        description: "Operating system of machine you install docker on"
        type: string
        default: linux
        required: true 
      distribution:
        description: "Linux distribution or Windows version"
        type: string 
        default: ubuntu 
        required: true 
    secrets:
      CHECKOUT_GHE_PAT: 
        description: "Personal access token for GitHub Enterprise Repo with shared pipelines"
        required: true

jobs: 
  install-docker: 
    runs-on: ['dp-runner' , 'dp-ci']   

    steps: 
      - name: Update apt cache and install prerequisites
        if: ${{ inputs.os == 'linux' && inputs.distribution == 'ubuntu' }}
        run: |
          sudo apt update
          sudo apt install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/${{ inputs.os }}/${{ inputs.distribution }}/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

      - name: Add repository to apt sources. 
        if: ${{ inputs.os == 'linux' && inputs.distribution == 'ubuntu' }}
        run: |
          sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/${{ inputs.os }}/${{ inputs.distribution }}
          Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
          Components: stable
          Architectures: $(dpkg --print-architecture)
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF
     
      - name: Update apt cache and install docker packages. 
        if: ${{ inputs.os == 'linux' && inputs.distribution == 'ubuntu' }}
        run: |
          sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
